#!/bin/bash

help() {
  echo "Usage:"
  echo "  gvm use"
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  echo $PLUGIN_GVM_GO_BIN
}

run() {
  core $@
}

run $@
