#!/bin/bash

help() {
  echo "Usage:"
  echo "  gvm exec"
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  gvm::exec $@
  if [ "$?" != "0" ]; then
    log::error "failed to exec: $@"
    exit 1
  fi
}

run() {
  core $@
}

run $@
