#!/bin/bash

help() {
  echo "Use LTS Version"
  echo ""
  echo "Usage:"
  echo "  gvm lts"
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  log::info "Use LTS Version $PLIGIN_GVM_GO_LTS_VERSION"

  gvm::use $PLIGIN_GVM_GO_LTS_VERSION
}

run() {
  core $@
}

run $@
