#!/bin/bash

load inquirer

help() {
  echo "Usage:"
  echo "  gvm use"
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  local version=$1

  if [ -z "$version" ]; then
    local availables=($(gvm::list))
    inquirer::select "Select ?" availables version
  fi

  gvm::use $version

  echo "current: $version ($(go version))"
}

run() {
  core $@
}

run $@
