#!/bin/bash

gvm::list_remote() {
  local versions=$(git ls-remote -t https://github.com/golang/go | awk -F/ '{ print $NF }' | grep go | awk -F go '{print $2}')
  # local versions=""
  # for version in ${_versions[@]}; do
  #   versions="v$version $versions"
  # done
  
  for version in ${versions[@]}; do
    echo $version
  done
}


export -f gvm::list_remote
