#!/bin/bash

# gvm::remove remove the go version
# if the version is current, it will be unset
gvm::remove() {
  local version=$1
  if [ -z "$version" ]; then
    log::error "[gvm::use] version is required"
    return 1
  fi

  # smart detect
  version=$(vm::version_ensure_prefix_v $version)

  if [ ! -d "$PLUGIN_GVM_VERSIONS/$version" ]; then
    log::error "[gvm::use] version $version not found"
    return 1
  fi

  sudo rm -rf $PLUGIN_GVM_VERSIONS/$version

  if [ "$(gvm::current)" == "$version" ]; then
    local new_version=$(gvm::list | head -n 1)
    if [ -n "$new_version" ]; then
      gvm::use $new_version
    else
      echo "" >$PLUGIN_GVM_VERSION_CURRENT
    fi
  fi
}

export -f gvm::remove
