#!/bin/bash

# gvm::use change the current version of go
gvm::use() {
  local version=$1
  if [ -z "$version" ]; then
    log::error "[gvm::use] version is required"
    return 1
  fi

  # smart detect
  version=$(vm::version_ensure_prefix_v $version)

  if [ ! -d "$PLUGIN_GVM_VERSIONS/$version" ]; then
    # log::error "[gvm::use] version $version not found"
    # exit 1
    gvm::install $version
    gvm::use $version
    return
  fi

  # @TODO force sudo
  sudo ls >>/dev/null 2>&1

  if [ -d $PLUGIN_GVM_GO_HOME ]; then
    # if not a link
    file $PLUGIN_GVM_GO_HOME | grep symbolic >>/dev/null 2>&1
    if [ "$?" != "0" ]; then
      sudo rm -rf $PLUGIN_GVM_GO_HOME
    else
      sudo rm -f $PLUGIN_GVM_GO_HOME
    fi
  fi

  if [ ! -d "/usr/local/bin" ]; then
    sudo mkdir -p /usr/local/bin
  fi

  sudo ln -sf $PLUGIN_GVM_VERSIONS/$version $PLUGIN_GVM_GO_HOME
  sudo ln -sf $PLUGIN_GVM_GO_HOME/bin/go /usr/local/bin/go
  echo $version >$PLUGIN_GVM_VERSION_CURRENT

  # apply env
  gvm::env
}

export -f gvm::use
